-- Create Database
CREATE DATABASE IF NOT EXISTS QuanLyVatTu;
USE QuanLyVatTu;

-- 1. Bảng Nhà Cung Cấp
CREATE TABLE NHACC (
    MaNCC INT AUTO_INCREMENT PRIMARY KEY,
    TenNCC VARCHAR(150) NOT NULL,
    DiaChi VARCHAR(255)
);

-- 2. Bảng Số Điện Thoại Nhà Cung Cấp (Thuộc tính đa trị SDT)
CREATE TABLE NHACC_SDT (
    MaNCC INT NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    PRIMARY KEY (MaNCC, SDT),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC) ON DELETE CASCADE
);

-- 3. Bảng Vật Tư
CREATE TABLE VATTU (
    MaVTU INT AUTO_INCREMENT PRIMARY KEY,
    TenVTU VARCHAR(100) NOT NULL
);

-- 4. Bảng Đơn Đặt Hàng (Mối quan hệ 1-N với NHACC)
CREATE TABLE DONDH (
    SoDH INT AUTO_INCREMENT PRIMARY KEY,
    NgayDH DATE NOT NULL,
    MaNCC INT NOT NULL,
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

-- 5. Bảng Chi Tiết Đơn Đặt Hàng (Mối quan hệ 3 N-N)
CREATE TABLE CHITIET_DONDH (
    SoDH INT NOT NULL,
    MaVTU INT NOT NULL,
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- 6. Bảng Phiếu Nhập
CREATE TABLE PHIEUNHAP (
    SoPN INT AUTO_INCREMENT PRIMARY KEY,
    NgayNhap DATE NOT NULL
);

-- 7. Bảng Chi Tiết Phiếu Nhập (Mối quan hệ 2 N-N)
CREATE TABLE CHITIET_PHIEUNHAP (
    SoPN INT NOT NULL,
    MaVTU INT NOT NULL,
    DGNhap DECIMAL(12, 2) NOT NULL CHECK (DGNhap >= 0),
    SLNhap INT NOT NULL CHECK (SLNhap > 0),
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

-- 8. Bảng Phiếu Xuất
CREATE TABLE PHIEUXUAT (
    SoPX INT AUTO_INCREMENT PRIMARY KEY,
    NgayXuat DATE NOT NULL
);

-- 9. Bảng Chi Tiết Phiếu Xuất (Mối quan hệ 1 N-N)
CREATE TABLE CHITIET_PHIEUXUAT (
    SoPX INT NOT NULL,
    MaVTU INT NOT NULL,
    DGXuat DECIMAL(12, 2) NOT NULL CHECK (DGXuat >= 0),
    SLXuat INT NOT NULL CHECK (SLXuat > 0),
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);